package main

import (
	"strings"
	"github.com/MohamedRach/dgrep/src/mr"
)

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
func Map(content string, target string) []mr.KeyValue {
	
  kva := []mr.KeyValue{}

	// Iterate through each line
  for _, line := range content {
		// Check if the line contains the specified word
		if strings.Contains(string(line), target) {
      kv := mr.KeyValue{
        Key: string(line),
        Value: "1",
      }
      kva = append(kva, kv)
    }
	}	
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string) string {
	// return the number of occurrences of this word.
	return key
}
